### ISSUE TITLE
is simple oracledb or oracledb delete null column result ?

### ISSUE THREAD

**Issue by behroozshafiabadi** [sagiegurari/simple-oracledb#9]
when i execute select query on table,some json object results have not property that are null in the table.
this cause my app throw error...is that a way to avoid this accidence ?
is this happen ?

**Comment by sagiegurari** [comment]
you sure the properties are missing and not there with value of type undefined?
I have a test that inserts 2 rows and sets 4 columns for each row. but the table holds 6 columns.
In the query output, i get all 6 columns where the other 2 are set to undefined.
You can see the test code here:
https://github.com/sagiegurari/simple-oracledb/blob/3516aa9f3eac3294fb18542d0611a49aa1816719/test/spec/integration-spec.js#L155-L194

**Comment by behroozshafiabadi** [comment]
yes it's my fault they are undefined.
is that any way to return empty string instead of undefined ?

**Comment by sagiegurari** [comment]
oracle (and i'm not close to be an expert like the oracle team) has no concept of empty string.
**when you insert empty string, it pushes null.**
so when you query, you can't query by empty string, you query by is null.
so when you pull data that is 'empty string' it is basically null.
so in my layer, i always get undefined, no matter if you pushed empty string or null, because it is always stored in the db as null.
one of those strange oracle behaviors.

**Comment by behroozshafiabadi** [comment]
thanks your says are very useful
